#+TITLE: Pollsposition
#+SUBTITLE: Questions
#+AUTHOR: Rémi Louf, Alexandre Andorra
#+DATE: 2022-03-04
#+EMAIL: remilouf@gmail.com

#+STARTUP: hideblocks overview
#+OPTIONS: \n:t H:4 toc:1

#+SETUPFILE: latex-setup.org

#+PROPERTY: header-args:latex   :results raw :exports results
#+PROPERTY: header-args:python :eval no-export :noweb strip-export :exports none

#+LATEX: \newpage
* Est-ce que l'on peut prédire le résultat d'une élection ?
:PROPERTIES:
:UNNUMBERED: t
:END:
#+LATEX: \newpage
* Est-ce qu'il peut y avoir des conflit d'intérêts entre sondeurs et candidats ?
:PROPERTIES:
:UNNUMBERED: t
:END:
#+LATEX: \newpage
* Les sondages sont-ils correctement traités dans les médias ?
:PROPERTIES:
:UNNUMBERED: t
:END:

Je pense que l'on n'existerait pas si les médias faisaient correctement leur travail.

On voit quelques petites irrégularités de temps à autres, notamment sur l'annonce des tailles d'échantillons. Les journaux, clients des instituts de sondage pourraient demander aux instituts de fournir les chiffres dans leur notice. Mais ils ne le font pas. Je pense que l'effet course de chevaux les arrange quelque part: c'est ce qui créée de la nouveauté, c'est ce qui attire l'attention.

Notre temps d'analyse est donc autant que possible détaché de l'actualité médiatique. Ce qui implique parfois trépigner d'impatience derrière notre clavier à attendre la taille d'échantillon d'un sondage pour pouvoir mettre nos chiffres à jour. Mais ce temps est important, le temps entre deux mises à jour est important, car il laisse le débat démocratique, autrement pris en otage par la constante nouveauté, respirer.
#+LATEX: \newpage

* Le score d'Eric Zemmour est-il sous-évalué dans les sondages ?
:PROPERTIES:
:UNNUMBERED: t
:END:

C'est une excellente question car elle touche à la fois à la question du redressement dans les sondages et à la façon dont notre modèle fonctionne.

L'hypothèse derrière cette question est je pense que les instituts redressent les résultats des sondages sur les résultats des élections passées. C'est effectivement ce que semblent faire certains instituts, car cela diminuerait sensiblement les biais de non réponse [[cite:&gelman2016]]. Or comme vous le faites remarquer la candidature d'Eric Zemmour est particulière car il ne vient "de nulle part", et sa candidature est encore plus innovante pour le système politique français que celle d'Emmanuel Macron en 2017. Les sondeurs utilisent néanmoins je pense la méthode des quotas pour faire en sorte que l'échantillon interrogé /ressemble/ à la population globale.

Impossible de savoir si son score est sur- ou sous-estimé en revanche, en tout cas de façon quantitative. En revanche on devrait s'attendre à une variabilité plus grande au fil du temps, qui s'expliquera non pas par un électorat fluctuant, mais pas une tendance de son électorat à répondre aux sondages qui fluctue. On peut maintenant passer des heures sur un plateau télé à discuter des raisons pour lesquelles un électeur potentiel de Zemmour aurait envie ou non de répondre à un sondage, mais ça n'irait nulle part. On parlera sûrement de l'électorat fluctuant d'Eric Zemmour, mais vous savez maintenant mieux que les commentateurs [[cite:&gelman2016]]

Le fait qu'Eric Zemmour ne se soit pas présenté auparavant (ou son parti) pose également des problèmes à notre modèle qui est incapable de construire une trajectoire /a priori/ du candidat Zemmour. Cependant, les idées partagées par Zemmour ne sont pas tout à fait nouvelles, et on peut ranger les partis politiques dans des catégories un peu plus grandes, les familles politiques. Pour caricaturer l'extrême gauche, la gauche, la droite, l'extrême droite, les identitaires, etc. C'est quelque chose à garder en tête lorsque l'on analaysera les résultats du modèle.

#+LATEX: \newpage

***** TODO Bibliography

#+begin_src latex
\bibliographystyle{plain}
\bibliography{bibliography}
#+end_src
